"""Initial relational schema

Revision ID: 1bdc369a9063
Revises: 
Create Date: 2026-09-25 07:42:21.909579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdc369a9063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('level', sa.String(length=40), nullable=True),
    sa.Column('course_type', sa.String(length=40), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exam_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('workbook_hash', sa.String(length=64), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_year'), ['year'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingestion_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('exam_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=True),
    sa.Column('variant', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_type.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity')
    )
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_exam_type_id'), ['exam_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_term_id'), ['term_id'], unique=False)

    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_user_id'), ['user_id'], unique=False)

    op.create_table('ingestion_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('extracted', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batch.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    with op.batch_alter_table('ingestion_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_file_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_file_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_file_status'), ['status'], unique=False)

    op.create_table('source_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('workbook_hash', sa.String(length=64), nullable=False),
    sa.Column('sheet', sa.String(length=100), nullable=False),
    sa.Column('cell', sa.String(length=20), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('answer_status', sa.String(length=40), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('negative_marks', sa.Float(), nullable=True),
    sa.Column('tolerance', sa.Float(), nullable=True),
    sa.Column('topic', sa.String(length=150), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('ingestion_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_file_id'], ['ingestion_file.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_topic'), ['topic'], unique=False)

    op.create_table('attempt_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('visited', sa.Boolean(), nullable=True),
    sa.Column('marked', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('awarded', sa.Float(), nullable=True),
    sa.Column('manual_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id')
    )
    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answer_attempt_id'), ['attempt_id'], unique=False)

    op.create_table('bookmark',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.create_table('question_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('alt', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_image_question_id'), ['question_id'], unique=False)

    op.create_table('question_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'key')
    )
    with op.batch_alter_table('question_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_option_question_id'), ['question_id'], unique=False)

    op.create_table('question_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_review_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_review_question_id'))

    op.drop_table('question_review')
    with op.batch_alter_table('question_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_option_question_id'))

    op.drop_table('question_option')
    with op.batch_alter_table('question_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_image_question_id'))

    op.drop_table('question_image')
    op.drop_table('bookmark')
    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answer_attempt_id'))

    op.drop_table('attempt_answer')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_topic'))
        batch_op.drop_index(batch_op.f('ix_question_status'))
        batch_op.drop_index(batch_op.f('ix_question_paper_id'))

    op.drop_table('question')
    op.drop_table('source_entry')
    with op.batch_alter_table('ingestion_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_file_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_file_paper_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_file_batch_id'))

    op.drop_table('ingestion_file')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_status'))
        batch_op.drop_index(batch_op.f('ix_attempt_paper_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_deadline'))

    op.drop_table('attempt')
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_term_id'))
        batch_op.drop_index(batch_op.f('ix_paper_status'))
        batch_op.drop_index(batch_op.f('ix_paper_exam_type_id'))
        batch_op.drop_index(batch_op.f('ix_paper_course_id'))

    op.drop_table('paper')
    op.drop_table('ingestion_batch')
    op.drop_table('user')
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_year'))

    op.drop_table('term')
    op.drop_table('import_run')
    op.drop_table('exam_type')
    op.drop_table('course')
    # ### end Alembic commands ###
