"""Track visited versus cleared responses

Revision ID: c60248414d44
Revises: 1bdc369a9063
Create Date: 2026-09-25 07:44:27.102716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60248414d44'
down_revision = '1bdc369a9063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_touched', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.drop_column('response_touched')

    # ### end Alembic commands ###
