import {it,expect,vi} from 'vitest';import {mount,flushPromises} from '@vue/test-utils';import AISolutions from '../src/AISolutions.vue';import SearchableSelect from '../src/SearchableSelect.vue';
const mocks=vi.hoisted(()=>({api:vi.fn()}));vi.mock('../src/api',()=>mocks);
it('uses course search then exam then paper, shows statistics, and removes worker controls',async()=>{
 mocks.api.mockImplementation(async path=>path==='/catalog'?{courses:[{id:1,name:'Game Theory',code:'GT'}]}:path==='/metadata'?{exams:[{id:2,name:'Quiz 1'}]}:path.startsWith('/admin/ai-solutions/summary')?{papers:[{id:3,name:'Paper',term:'May 2026',questions:4,uploaded:2,published:0}],statistics:{papers_total:1,papers_complete:0,papers_pending:1,papers_published:0,questions_total:4,questions_uploaded:2,questions_pending:2,questions_review:2}}:{items:[],total:0});
 const w=mount(AISolutions);await flushPromises();expect(w.text()).not.toContain('Generate');expect(w.text()).not.toContain('Worker');expect(w.text()).toContain('50%');expect(w.findAll('select')).toHaveLength(2);expect(w.get('[aria-label="Choose solution exam"]').attributes('disabled')).toBeDefined();
 await w.get('[aria-label="Choose solution course"]').trigger('click');await w.get('[aria-label="Search options"]').setValue('gt');expect(w.findAll('.searchable-select-option')).toHaveLength(1);await w.get('.searchable-select-option').trigger('click');await flushPromises();expect(w.get('[aria-label="Choose solution exam"]').attributes('disabled')).toBeUndefined();expect(w.get('[aria-label="Choose solution paper"]').attributes('disabled')).toBeDefined();
 await w.get('[aria-label="Choose solution exam"]').setValue(2);await flushPromises();expect(w.get('[aria-label="Choose solution paper"]').attributes('disabled')).toBeUndefined();await w.get('[aria-label="Choose solution paper"]').setValue(3);await flushPromises();expect(w.find('textarea').exists()).toBe(true);expect(mocks.api.mock.calls.some(([p])=>p.startsWith('/admin/ai-solutions?paper_id=3'))).toBe(true);
 w.findComponent(SearchableSelect).vm.$emit('update:modelValue','');w.findComponent(SearchableSelect).vm.$emit('change','');await flushPromises();expect(w.find('textarea').exists()).toBe(false);expect(w.get('[aria-label="Choose solution exam"]').element.value).toBe('');w.unmount();
});
