<script setup>
import {ref,onMounted,onUnmounted} from 'vue';import {api,loadCatalog,invalidateCatalog,session} from './api';import MathText from './MathText.vue';import Upload from './Upload.vue';
const uploadForm=ref(null);
const tab=ref('Processing'),tabs=['Processing','Upload PDFs','Papers','Question bank','Catalog','Settings'];
const stats=ref({}),jobs=ref([]),questions=ref([]),courses=ref([]),papers=ref([]),adminPapers=ref([]),meta=ref({terms:[],exams:[]}),course=ref(''),paper=ref(''),files=ref([]),error=ref(''),notice=ref(''),busy=ref(false),page=ref(1),total=ref(0),settings=ref({}),detail=ref(null),paperSearch=ref(''),paperStatus=ref(''),editPaper=ref(null),manageCourse=ref(''),newPaper=ref({name:'',term_id:'',exam_type_id:'',session:''}),newTerm=ref({kind:'term',name:'',year:2026,month:9});let timer;
async function run(fn){busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
async function refresh(){stats.value=await api('/admin/stats');if(tab.value==='Processing'){const d=await api('/admin/ingestion?page='+page.value);jobs.value=d.items;total.value=d.total}else if(tab.value==='Papers'){const d=await api('/admin/papers?'+new URLSearchParams({page:page.value,limit:24,q:paperSearch.value,status:paperStatus.value,course_id:manageCourse.value}));adminPapers.value=d.items;total.value=d.total}else if(tab.value==='Question bank'){const d=await api('/admin/questions?'+new URLSearchParams({page:page.value,paper_id:paper.value}));questions.value=d.items;total.value=d.total}else if(tab.value==='Settings')settings.value=await api('/admin/settings')}
async function chooseTab(t){tab.value=t;page.value=1;detail.value=null;await run(refresh)}
async function loadPapers(){papers.value=(await api('/papers?limit=100&course_id='+course.value)).items;paper.value=''}
async function queue(retry=false){await run(async()=>{const d=await api('/admin/process-catalog',{method:'POST',body:{retry}});notice.value=d.queued+' sources queued. The worker automatically downloads, extracts and makes reliable questions available.';await refresh()})}
function chooseFiles(e){files.value=Array.from(e.target.files).map(file=>({file,paper_id:paper.value}))}
async function upload(){await run(async()=>{if(files.value.some(f=>!f.paper_id))throw Error('Choose a paper for each PDF.');const form=new FormData();files.value.forEach(f=>form.append('files',f.file));form.append('paper_ids',JSON.stringify(files.value.map(f=>Number(f.paper_id))));const d=await api('/admin/papers/bulk-upload',{method:'POST',form});notice.value='Batch '+d.batch_id+' accepted. Extraction and availability are automatic; no approval is needed.';files.value=[];await refresh()})}
async function importWorkbook(e){if(!e.target.files[0])return;await run(async()=>{const form=new FormData();form.append('file',e.target.files[0]);const d=await api('/admin/catalog',{method:'POST',form});notice.value=`Catalog imported: ${d.new_papers} new entries; ${d.queued} sources automatically queued.`;await refreshCatalog();await refresh()})}
async function createPaper(){await run(async()=>{if(!manageCourse.value)throw Error('Choose a course.');const d=await api('/admin/papers',{method:'POST',body:{...newPaper.value,course_id:Number(manageCourse.value),term_id:Number(newPaper.value.term_id),exam_type_id:Number(newPaper.value.exam_type_id)}});notice.value='Paper created. You can upload its PDF from Upload PDFs.';newPaper.value={name:'',term_id:'',exam_type_id:'',session:''};invalidateCatalog();await refreshCatalog();await refresh()})}
async function savePaper(){if(!editPaper.value)return;await run(async()=>{const p=editPaper.value;await api('/admin/papers/'+p.id,{method:'PATCH',body:{name:p.name,course_id:Number(p.course_id),term_id:Number(p.term_id),exam_type_id:Number(p.exam_type_id),session:p.session||'',duration_seconds:p.duration_seconds||null,source_url:p.source_url||null}});notice.value='Paper updated.';editPaper.value=null;invalidateCatalog();await refreshCatalog();await refresh()})}
async function archivePaper(p){if(!confirm('Hide this paper from students? Existing attempt snapshots remain safe.'))return;await run(async()=>{await api('/admin/papers/'+p.id+'/archive',{method:'POST',body:{}});notice.value='Paper archived and hidden from student pages.';invalidateCatalog();await refreshCatalog();await refresh()})}
async function restorePaper(p){await run(async()=>{await api('/admin/papers/'+p.id+'/restore',{method:'POST',body:{}});notice.value='Paper restored.';invalidateCatalog();await refreshCatalog();await refresh()})}
async function deletePaper(p){if(!confirm('Permanently delete this catalog paper? This is allowed only when it has no linked questions, imports, attempts or progress.'))return;await run(async()=>{await api('/admin/papers/'+p.id,{method:'DELETE'});notice.value='Paper permanently deleted.';invalidateCatalog();await refreshCatalog();await refresh()})}
async function refreshCatalog(){invalidateCatalog();const catalog=await loadCatalog();courses.value=catalog.courses;meta.value=catalog.meta;await uploadForm.value?.refreshCatalog()}
onMounted(async()=>{if(session.user?.role!=='ADMIN')return;await run(async()=>{const catalog=await loadCatalog();courses.value=catalog.courses;meta.value=catalog.meta;await refresh()});timer=setInterval(()=>{if(tab.value==='Processing')refresh().catch(e=>error.value=e.message)},6000)});onUnmounted(()=>clearInterval(timer));
</script>
<template><section v-if="session.user?.role!=='ADMIN'" class="empty panel"><h1>Administrator access required</h1><a href="#/login" class="btn btn-primary">Sign in</a></section><template v-else><div class="eyebrow">AUTOMATIC QUESTION BANK</div><h1>Processing & sources</h1><p class="muted">Upload once. Reliable questions become available automatically.</p><nav class="admin-tabs"><button v-for="t in tabs" :class="{active:tab===t}" @click="chooseTab(t)">{{t}}</button></nav><div v-if="error" class="alert alert-danger" role="alert">{{error}}</div><div v-if="notice" class="alert alert-success" role="status">{{notice}}</div>
<template v-if="tab==='Processing'"><div class="admin-stat-grid"><div class="panel" v-for="k in ['papers','processed','processing','failed','questions','flagged_questions']"><span class="eyebrow">{{k.replaceAll('_',' ')}}</span><strong>{{stats[k]??0}}</strong></div></div><details class="panel my-4"><summary>Bulk processing is paused — advanced controls</summary><div class="d-flex gap-3 flex-wrap my-4"><button class="btn btn-primary" :disabled="busy" @click="queue(false)">Resume full catalog processing</button><button class="btn btn-outline-primary" :disabled="busy" @click="queue(true)">Retry all failed sources</button><button class="btn btn-light" @click="run(refresh)">Refresh</button></div></details><article class="panel job-card" v-for="f in jobs"><div class="section-row"><strong>#{{f.paper_id}} · {{f.filename}}</strong><span class="status">{{f.status}}</span></div><p class="muted small">{{f.extracted}} question records · {{f.pages??'—'}} pages · {{f.retries}} retries</p><a v-if="f.source_url" :href="f.source_url" target="_blank" rel="noopener noreferrer">Source link ↗</a><p v-if="f.error" class="alert alert-danger mt-3">{{f.error}}</p><details class="mt-3"><summary>Processing evidence & logs</summary><pre>{{JSON.stringify({events:f.events,warnings:f.warnings,duplicate_of:f.duplicate_of_id},null,2)}}</pre></details><button v-if="['PROCESSING_FAILED','EXTRACTION_FAILED'].includes(f.status)" class="btn btn-light mt-3" @click="run(async()=>{await api('/admin/ingestion/'+f.id+'/retry',{method:'POST'});await refresh()})">Retry processing</button></article><p v-if="!jobs.length" class="empty panel">No processing jobs yet.</p></template>
<div v-if="tab==='Question bank'" class="filters"><select class="form-select" v-model="course" @change="run(loadPapers)" aria-label="Course"><option value="">Select course</option><option v-for="c in courses" :value="c.id">{{c.code}} · {{c.name}}</option></select><select class="form-select" v-model="paper" @change="page=1;run(refresh)" aria-label="Paper"><option value="">Select paper</option><option v-for="p in papers" :value="p.id">{{p.term}} · {{p.exam}} {{p.session}} · {{p.name}}</option></select></div>
<template v-if="tab==='Upload PDFs'"><Upload ref="uploadForm"/><details class="panel mb-4"><summary>Add a new term/year</summary><form @submit.prevent="run(async()=>{await api('/admin/metadata',{method:'POST',body:newTerm});await refreshCatalog();notice='Term added'})"><div class="form-grid"><label>Term name<input class="form-control" v-model="newTerm.name" placeholder="January 2027" required></label><label>Year<input type="number" v-model="newTerm.year" class="form-control" required></label><label>Month<input type="number" min="1" max="12" v-model="newTerm.month" class="form-control" required></label></div><button class="btn btn-primary mt-3">Add term</button></form></details></template>
<template v-if="tab==='Question bank'"><article class="panel mb-3" v-for="q in questions"><div class="section-row"><h3>Question {{q.number}} · {{q.kind}}</h3><span class="status">{{q.status}}</span></div><MathText :text="q.text"/><p class="small muted">Source pages: {{q.source_pages?.join(', ')||q.source_page}} · confidence {{Math.round(q.confidence*100)}}%</p><details><summary>Extraction metadata</summary><pre>{{JSON.stringify({answers:q.answers,marks:q.marks,negative_marks:q.negative_marks,evidence:q.evidence,warnings:q.warnings},null,2)}}</pre></details></article><p v-if="!questions.length" class="empty panel">Questions appear here after automatic processing.</p></template>
<template v-if="tab==='Catalog'"><section class="panel"><h2>Import Excel catalog</h2><p class="muted">Bulk processing is paused. The workbook updates the complete catalog without starting downloads. Reimporting does not duplicate question records.</p><input type="file" accept=".xlsx" class="form-control" @change="importWorkbook" :disabled="busy" aria-label="Excel workbook"></section></template>
<section class="panel" v-if="tab==='Settings'"><h2>Extraction services</h2><dl class="settings-list"><template v-for="(v,k) in settings"><dt>{{k.replaceAll('_',' ')}}</dt><dd>{{String(v)}}</dd></template></dl><p class="muted">Native PDF colour/layout extraction runs automatically. Configured models assist extraction; source indicators always take precedence. Secrets remain on the server.</p></section>
<div v-if="['Processing','Question bank'].includes(tab)&&total>24" class="pagination-row"><button class="btn btn-light" :disabled="page===1" @click="page--;run(refresh)">Previous</button><span>Page {{page}}</span><button class="btn btn-light" :disabled="page*24>=total" @click="page++;run(refresh)">Next</button></div></template></template>
