<script setup>
import PaperProgress from './PaperProgress.vue';
import {ref,onMounted} from 'vue';import {ArrowUpRight,Search,FileText,BookOpen,CheckCircle2,ChevronRight,Filter} from 'lucide-vue-next';
import {api,session,go} from './api';
const props=defineProps({route:String});const stats=ref({}),courses=ref([]),course=ref(null),paper=ref(null),papers=ref([]),meta=ref({levels:[]}),q=ref(''),level=ref(''),sort=ref('name'),exam=ref(''),year=ref(''),term=ref(''),page=ref(1),total=ref(0),error=ref(''),loading=ref(true),topics=ref([]),timedMinutes=ref(90);
const featured=ref([]);
const isCourse=props.route.startsWith('/course/'),isPaper=props.route.startsWith('/paper/');
async function load(){loading.value=true;try{if(isCourse){const d=await api('/papers?'+new URLSearchParams({course_id:course.value.id,exam:exam.value,year:year.value,term_id:term.value,page:page.value,limit:16}));papers.value=d.items;total.value=d.total}else if(!isPaper){const d=await api('/courses?'+new URLSearchParams({q:q.value,level:level.value,sort:sort.value,page:page.value,limit:12}));courses.value=d.items;total.value=d.total}}catch(e){error.value=e.message}finally{loading.value=false}}
async function filter(){page.value=1;await load()}
onMounted(async()=>{try{
 if(isPaper){const id=props.route.split('/')[2];paper.value=await api('/papers/'+id);loading.value=false;if(paper.value.practice_available)void api('/papers/'+id+'/questions?page=1&limit=1').catch(()=>{});return}
 if(isCourse){[course.value,meta.value]=await Promise.all([api('/courses/'+props.route.split('/')[2]),api('/metadata')]);await Promise.all([load(),api('/courses/'+course.value.id+'/topics').then(d=>topics.value=d)]);return}
 await Promise.all([load(),api('/stats').then(d=>stats.value=d),api('/demo-papers').then(d=>featured.value=d.items||[]),api('/metadata').then(d=>meta.value=d)]);
}catch(e){error.value=e.message;loading.value=false}});
async function start(mode){if(!session.user)return go('/login');try{const a=await api('/attempts',{method:'POST',body:{paper_id:paper.value.id,mode,duration_seconds:Number(timedMinutes.value)*60}});go('/attempt/'+a.id)}catch(e){error.value=e.message}}
async function topicStart(topic){if(!session.user)return go('/login');try{const a=await api('/attempts',{method:'POST',body:{collection:'topic',course_id:course.value.id,topic,mode:'practice'}});go('/attempt/'+a.id)}catch(e){error.value=e.message}}
</script>
<template>
<div v-if="error" class="alert alert-danger" role="alert">{{error}}</div>
<template v-if="!isCourse&&!isPaper"><div class="eyebrow">THE PAPER LIBRARY</div><div class="section-row intro"><div><h1>Practice with purpose.</h1><p>Find your course. Choose a paper. Make every attempt count.</p></div><div class="library-stamp"><BookOpen :size="32"/><span>YOUR NEXT<br><strong>breakthrough starts here.</strong></span></div></div>
<nav class="exam-type-cards" aria-label="Choose exam type"><a v-for="name in ['Quiz 1','Quiz 2','End Term']" :href="'#/exam/'+encodeURIComponent(name)" class="exam-type-card"><strong>{{name}}</strong><span>Select course &amp; paper →</span></a></nav><div class="stats-row"><div><span class="stat-icon"><BookOpen :size="21"/></span><strong>{{stats.courses??'—'}}</strong><span>Courses</span></div><div><span class="stat-icon"><FileText :size="21"/></span><strong>{{stats.papers??'—'}}</strong><span>Catalog papers</span></div><div><span class="stat-icon green"><CheckCircle2 :size="21"/></span><strong>{{stats.questions??'—'}}</strong><span>Available questions</span></div><div class="stats-note">Source papers are ready to browse.<br>Questions appear automatically after extraction.</div></div>
<section v-if="featured.length" class="my-4"><div class="section-row"><h2>Five papers to try</h2><span class="muted small">Real extracted PYQs</span></div><div class="course-grid"><a v-for="p in featured" :href="'#/paper/'+p.id" class="course-card panel"><span class="eyebrow">{{p.exam}} · {{p.term}}</span><h3>{{p.course}}</h3><p>{{p.question_count}} questions · {{p.total_marks??'—'}} marks</p><PaperProgress :progress="p.progress"/><span class="btn btn-outline-primary">{{p.progress?.attempted?'Retake Test':'Take Test'}} →</span></a></div></section><div class="section-row"><h2>Explore your courses <span class="count">{{total}}</span></h2><span class="muted small">From the supplied degree paper catalog</span></div><form class="filters" @submit.prevent="filter"><div class="input-icon"><Search :size="18"/><input class="form-control" v-model="q" placeholder="Find a course by name or code" aria-label="Find a course"></div><select class="form-select" v-model="level" @change="filter" aria-label="Course level"><option value="">All levels</option><option v-for="l in meta.levels">{{l}}</option></select><select class="form-select" v-model="sort" @change="filter" aria-label="Sort courses"><option value="name">Name A–Z</option><option value="papers">Most papers</option></select><button class="btn btn-primary">Search</button></form>
<p v-if="loading" class="muted">Loading courses…</p><div v-else class="course-grid"><a class="course-card" v-for="(c,i) in courses" :href="'#/course/'+c.id"><div class="section-row"><span class="course-monogram" :class="'tone-'+i%4">{{c.code?.slice(0,2)}}</span><span class="code">{{c.code}}</span></div><h3>{{c.name}}</h3><div class="course-meta">{{c.level?.replaceAll('_',' ')}} <span>·</span> {{c.course_type}}</div><div class="exam-tags"><span v-for="(n,e) in c.exams">{{e}} <b>{{n}}</b></span><span v-if="!c.paper_count">No linked papers yet</span></div><div class="course-card-footer"><span>{{c.paper_count}} papers <span class="muted">· {{c.years.length?Math.min(...c.years)+'–'+Math.max(...c.years):'No years yet'}}</span></span><ArrowUpRight :size="20"/></div></a></div><div v-if="!loading&&!courses.length" class="empty panel"><h3>No matching courses</h3><p>Try a different name, code or level.</p></div>
</template>
<template v-if="isCourse&&course"><a class="breadcrumb-link" href="#/">Library <ChevronRight :size="14"/> {{course.code}}</a><div class="eyebrow mt-4">{{course.level?.replaceAll('_',' ')}} · {{course.code}}</div><h1>{{course.name}}</h1><p class="muted">{{course.paper_count}} papers · {{course.question_count}} available questions</p><div class="category-row"><button class="category" :class="{selected:exam===''}" @click="exam='';filter()"><strong>All papers</strong><span>{{course.paper_count}}</span></button><button v-for="(n,e) in course.exams" class="category" :class="{selected:exam===e}" @click="exam=e;filter()"><strong>{{e}}</strong><span>{{n}} papers</span></button></div><div class="section-row"><h2>{{exam||'Available papers'}}</h2><select class="form-select year-filter" v-model="term" @change="filter" aria-label="Select term and year"><option value="">All terms / years</option><option v-for="t in meta.terms" :value="t.id">{{t.name}}</option></select></div><div v-for="p in papers" class="paper-row panel"><span class="paper-icon"><FileText/></span><div class="paper-info"><span class="eyebrow">{{p.exam}} · {{p.term}} {{p.session?'· '+p.session:''}}</span><h3>{{p.name}}</h3><PaperProgress :progress="p.progress"/><span class="muted small">{{p.question_count?p.question_count+' available questions':'Questions not imported yet.'}}</span></div><span class="status" :class="{ready:p.practice_available}">{{p.practice_available?'Practice available':'Source catalog'}}</span><a :href="'#/paper/'+p.id" class="btn btn-outline-primary">{{p.practice_available?(p.progress?.attempted?'Retake Test':'Take Test'):'Open paper'}} <ChevronRight :size="16"/></a></div><div v-if="!papers.length&&!loading" class="empty panel"><h3>No papers in this selection</h3><p>Only available catalog entries are shown.</p></div><div v-if="topics.length" class="panel mt-4"><h2>Practice by topic</h2><button v-for="t in topics" class="btn btn-light me-2" @click="topicStart(t.topic)">{{t.topic}} · {{t.count}}</button></div></template>
<template v-if="isPaper&&paper"><a :href="'#/course/'+paper.course_id" class="breadcrumb-link">{{paper.course}} <ChevronRight :size="14"/> {{paper.exam}}</a><div class="paper-detail panel"><span class="eyebrow">{{paper.term}} · {{paper.exam}} {{paper.session?'· '+paper.session:''}}</span><h1>{{paper.name}}</h1><PaperProgress :progress="paper.progress"/><p class="muted">{{paper.course}} · {{paper.code}}</p><div class="detail-metrics"><div><strong>{{paper.question_count}}</strong>Available questions</div><div><strong>{{paper.duration_seconds?Math.round(paper.duration_seconds/60)+' min':'Not in source'}}</strong>Exam duration</div><div><strong>{{paper.total_marks??'—'}}</strong>Extracted total marks</div><div><strong>{{paper.source_metadata?.declared_total_marks??'—'}}</strong>Source total marks</div></div><div v-if="!paper.practice_available" class="notice"><FileText :size="22"/><div><strong>Questions not imported yet.</strong><p>You can open the original source. Practice and exams become available after automatic processing.</p></div></div><p v-if="paper.status==='PARTIALLY_AVAILABLE'" class="alert alert-warning">Only the reliably extracted subset is available. This is not yet the complete original paper.</p><p v-if="paper.source_metadata?.discrepancies?.length" class="muted small">The source header and extracted content differ in {{paper.source_metadata.discrepancies.length}} recorded checks. Source values are preserved; no missing content is invented.</p><p v-if="paper.unknown_keys" class="muted small">{{paper.unknown_keys}} questions have no reliable source answer key and will be reported as ungraded.</p><div v-for="w in paper.warnings" class="alert alert-warning">{{w}}</div><label v-if="paper.practice_available" class="mb-3">Exam timer (minutes)<input type="number" min="1" max="480" v-model="timedMinutes" class="form-control numeric-answer"><small>Default: 90 minutes. You can change this; the source duration shown above is preserved.</small></label><div class="d-flex gap-3 flex-wrap"><button class="btn btn-primary" @click="start('practice')" :disabled="!paper.practice_available">Start practice</button><button class="btn btn-outline-primary" @click="start('exam')" :disabled="!paper.practice_available">Start exam</button><a v-if="paper.download_url" :href="paper.download_url" class="btn btn-light">Download source PDF</a><a v-if="paper.source_url" :href="paper.source_url" target="_blank" rel="noopener noreferrer" class="btn btn-light">View source <ArrowUpRight :size="16"/></a></div><div class="mode-explainer"><div><h3>Practice mode</h3><p>Work at your pace. Check an answer after responding and bookmark questions for later.</p></div><div><h3>Exam mode</h3><p>A timed attempt with saved responses. Scores and solutions appear after submission.</p></div></div></div></template>
<div v-if="!isPaper&&total>(isCourse?16:12)" class="pagination-row"><button class="btn btn-light" :disabled="page===1" @click="page--;load()">Previous</button><span>Page {{page}} of {{Math.ceil(total/(isCourse?16:12))}}</span><button class="btn btn-light" :disabled="page*(isCourse?16:12)>=total" @click="page++;load()">Next</button></div>
</template>
