<script setup>
import {readBrowse,saveBrowse,rememberPaper} from './browseState';
import BusyFeedback from './BusyFeedback.vue';
import PaperProgress from './PaperProgress.vue';
import {computed,ref,onMounted} from 'vue';import {api,loadCatalog} from './api';import SearchableSelect from './SearchableSelect.vue';
const props=defineProps({route:String});const exam=decodeURIComponent(props.route.slice('/exam/'.length));const courses=ref([]),course=ref(''),papers=ref([]),terms=ref([]),term=ref(''),page=ref(1),total=ref(0),loading=ref(true),error=ref('');const courseOptions=computed(()=>courses.value.map(c=>({value:c.id,label:[c.code,c.name].filter(Boolean).join(' · ')}))),termOptions=computed(()=>[{value:'',label:'All available terms'},...terms.value.map(t=>({value:t.id,label:t.name}))]);
const restored=readBrowse(props.route);course.value=restored.course||'';term.value=restored.term||'';page.value=restored.page||1;
onMounted(async()=>{try{const catalog=await loadCatalog();courses.value=catalog.courses.filter(x=>x.exams?.[exam]);terms.value=catalog.meta.terms;if(course.value)await load(false)}catch(e){error.value=e.message}finally{loading.value=false}});
async function load(reset=true){if(reset)page.value=1;saveBrowse(props.route,{course:course.value,term:term.value,page:page.value});papers.value=[];total.value=0;if(!course.value)return;loading.value=true;error.value='';try{const d=await api('/papers?'+new URLSearchParams({exam,course_id:course.value,term_id:term.value,available:'true',page:page.value,limit:24}));papers.value=d.items;total.value=d.total}catch(e){error.value=e.message}finally{loading.value=false}}
</script>
<template><section class="exam-browser"><a href="#/" class="breadcrumb-link">Home → {{exam}}</a><div class="eyebrow mt-4">SELECT A COURSE</div><h1>{{exam}} previous-year papers</h1><p class="muted">Select your course to see papers ready for practice and exams.</p><p v-if="error" role="alert" class="alert alert-danger">{{error}}</p><div class="filters exam-browser-filters"><label>Course<SearchableSelect v-model="course" :options="courseOptions" placeholder="Select course" search-placeholder="Type course name or code…" aria-label="Choose course" ariaLabel="Choose course" @change="load()"/></label><label>Term / Year<SearchableSelect v-model="term" :options="termOptions" placeholder="All available terms" search-placeholder="Type term or year…" ariaLabel="Choose term" @change="load()"/></label></div><div v-if="loading" class="request-feedback"><BusyFeedback :label="course?'Loading papers…':'Loading courses…'"/></div><p v-else-if="!course" class="empty panel">Choose a course above.</p><template v-else><h2>{{total}} available {{total===1?'paper':'papers'}}</h2><div class="pyq-grid"><article v-for="p in papers" :key="p.id" class="pyq-card panel"><span class="eyebrow">{{p.exam}} {{p.session?'· '+p.session:''}}</span><h3>{{p.term}}</h3><PaperProgress :progress="p.progress"/><p class="muted small pyq-metrics">{{p.question_count}} questions · {{p.total_marks??'—'}} marks</p><a class="btn btn-outline-primary btn-sm" :href="'#/paper/'+p.id" @click="rememberPaper(p.id,props.route)">{{p.progress?.attempted?'Retake Test':'Take Test'}} →</a></article></div><p v-if="!loading&&!papers.length" class="empty panel">No extracted papers are available for this selection yet. The complete Excel catalog is still accessible from the course library.</p><div v-if="total>24" class="pagination-row"><button class="btn btn-light" :disabled="page===1" @click="page--;load(false)">Previous</button><span>Page {{page}}</span><button class="btn btn-light" :disabled="page*24>=total" @click="page++;load(false)">Next</button></div></template></section></template>
