<script setup>
import {ref,onMounted,onUnmounted,computed} from 'vue';import {Clock,Bookmark,ChevronLeft,ChevronRight,Flag,Check,WifiOff,BookOpen} from 'lucide-vue-next';
import {api,go,session} from './api';import {clock,answerText,paletteLabel} from './utils';import MathText from './MathText.vue';import QuestionContent from './QuestionContent.vue';import AnswerValue from './AnswerValue.vue';
const props=defineProps({id:Number});const attempt=ref(null),item=ref(null),index=ref(0),value=ref(null),error=ref(''),saving=ref(false),feedback=ref(null),confirm=ref(false),showPalette=ref(false),seconds=ref(null),saved=ref('All responses saved'),pending=ref(null);
const navigating=ref(false),switchDialog=ref(false),switchMinutes=ref(90),instructions=ref(false);
let ticker,poller,draftTimer,saveTask=null,serverNow=0,received=0;const dirty=ref(false);const draftKey='pyq-draft-'+props.id;const key='pyq-pending-'+props.id;
const current=computed(()=>attempt.value?.palette[index.value]);
async function sync(){try{const a=await api('/attempts/'+props.id);attempt.value=a;serverNow=a.server_time;received=performance.now();if(a.status!=='ACTIVE'){sessionStorage.removeItem(key);go('/result/'+a.id)}}catch(e){error.value=e.message}}
async function open(n){if(saving.value||navigating.value||pending.value||n<0||n>=attempt.value.palette.length)return;if(!await flushText())return;navigating.value=true;index.value=n;error.value='';feedback.value=null;try{const d=await api(`/attempts/${props.id}/questions/${current.value.question_id}`);item.value=d;value.value=d.answer;dirty.value=false;feedback.value=d.feedback||null;sessionStorage.setItem('pyq-position-'+props.id,String(n));const draft=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(draft?.question_id===current.value.question_id){value.value=draft.answer;dirty.value=true;draftTimer=setTimeout(flushText,350)}if(d.status!=='ACTIVE')return go('/result/'+props.id);await persist({question_id:current.value.question_id});}catch(e){error.value=e.message}finally{navigating.value=false}}
async function persist(data){saving.value=true;saved.value='Saving…';try{const result=await api(`/attempts/${props.id}/answers`,{method:'POST',body:data});const p=attempt.value.palette.find(p=>p.question_id===data.question_id);if(p)p.state=result.state;if(result.feedback)feedback.value=result.feedback;if('marked' in data&&item.value)item.value.marked=data.marked;pending.value=null;sessionStorage.removeItem(key);saved.value='All responses saved';error.value='';return true}catch(e){if(!e.status||e.status>=500){pending.value=data;sessionStorage.setItem(key,JSON.stringify(data));saved.value='Response pending — reconnect to save';}error.value=e.message;if(e.status===409)await sync();return false}finally{saving.value=false}}
async function retry(){if(pending.value)await persist(pending.value)}
function editText(v){value.value=v;dirty.value=true;feedback.value=null;saved.value='Unsaved response';sessionStorage.setItem(draftKey,JSON.stringify({question_id:current.value.question_id,answer:v}));clearTimeout(draftTimer);draftTimer=setTimeout(flushText,350)}
async function flushText(){
 clearTimeout(draftTimer);
 if(saveTask)await saveTask;
 if(!dirty.value)return !pending.value;
 if(saving.value||pending.value)return false;
 const qid=current.value?.question_id,draft=value.value;
 if(!qid)return true;
 saveTask=persist({question_id:qid,answer:draft});const ok=await saveTask;saveTask=null;
 if(ok&&current.value?.question_id===qid&&value.value===draft){dirty.value=false;sessionStorage.removeItem(draftKey)}
 else if(ok&&dirty.value)return flushText();
 return ok;
}
async function answer(v){clearTimeout(draftTimer);dirty.value=false;sessionStorage.removeItem(draftKey);value.value=v;feedback.value=null;await persist({question_id:current.value.question_id,answer:v})}
async function option(k){const kind=item.value.question.kind;await answer(kind==='MSQ'?(Array.isArray(value.value)&&value.value.includes(k)?value.value.filter(x=>x!==k):[...(Array.isArray(value.value)?value.value:[]),k]):[k])}
async function bookmark(){try{await api('/questions/'+current.value.question_id+'/bookmark',{method:item.value.bookmarked?'DELETE':'POST'});item.value.bookmarked=!item.value.bookmarked}catch(e){error.value=e.message}}
async function submit(){if(saving.value)return;if(seconds.value!==0&&!await flushText())return;if(pending.value&&seconds.value!==0){error.value='Save the pending response before submitting.';return}try{await api(`/attempts/${props.id}/submit`,{method:'POST'});sessionStorage.removeItem(key);sessionStorage.removeItem(draftKey);go('/result/'+props.id)}catch(e){error.value=e.message}}
async function markNext(){if(!await flushText())return;await persist({question_id:current.value.question_id,marked:true});if(!error.value&&index.value<attempt.value.palette.length-1)await open(index.value+1)}
function keyboard(e){if(!['ArrowLeft','ArrowRight'].includes(e.key)||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||confirm.value||switchDialog.value||instructions.value||e.target?.closest?.('input,textarea,select,[contenteditable="true"],[role="dialog"]'))return;e.preventDefault();open(index.value+(e.key==='ArrowRight'?1:-1))}
async function switchMode(){if(saving.value||pending.value||navigating.value)return;if(!await flushText())return;try{const next=await api('/attempts/'+props.id+'/switch-mode',{method:'POST',body:{mode:attempt.value.mode==='exam'?'practice':'exam',duration_seconds:Number(switchMinutes.value)*60}});sessionStorage.setItem('pyq-position-'+next.id,String(index.value));sessionStorage.removeItem(key);go('/attempt/'+next.id)}catch(e){error.value=e.message}}
function online(){retry();sync()}
onMounted(async()=>{try{await sync();if(!attempt.value||attempt.value.status!=='ACTIVE')return;const raw=sessionStorage.getItem(key);if(raw){pending.value=JSON.parse(raw);await retry()}await open(Math.min(Number(sessionStorage.getItem('pyq-position-'+props.id))||0,attempt.value.palette.length-1));window.addEventListener('keydown',keyboard);ticker=setInterval(()=>{seconds.value=attempt.value?.deadline?Math.max(0,Math.ceil(attempt.value.deadline-serverNow-(performance.now()-received)/1000)):null;if(seconds.value===0)submit()},1000);poller=setInterval(sync,15000);window.addEventListener('online',online)}catch(e){error.value=e.message}});
onUnmounted(()=>{clearInterval(ticker);clearInterval(poller);clearTimeout(draftTimer);window.removeEventListener('online',online);window.removeEventListener('keydown',keyboard)});
</script>
<template><div v-if="!session.user" class="empty panel"><h2>Sign in to continue</h2><a href="#/login" class="btn btn-primary">Sign in</a></div><template v-else-if="attempt"><header class="exam-header"><a class="exam-logo" href="#/progress"><BookOpen/> PYQstudio</a><div><span class="eyebrow">{{attempt.mode==='exam'?'TIMED EXAM':'PRACTICE SESSION'}}</span><h1>{{attempt.title}}</h1></div><button class="btn btn-light mode-switch" @click="switchDialog=true" :disabled="saving||!!pending||navigating">Switch to {{attempt.mode==='exam'?'practice':'exam'}}</button><button class="btn btn-light" @click="instructions=true">Instructions</button><div class="timer" :class="{urgent:seconds!==null&&seconds<120}"><Clock :size="19"/>{{seconds===null?'Untimed':clock(seconds)}}</div></header><div class="cbt-section-bar"><strong>Section 1 · Question paper</strong><span>{{session.user.name}} · {{attempt.mode==='exam'?'Exam mode':'Practice mode'}}</span></div><div v-if="error" class="alert alert-danger" role="alert">{{error}}<button v-if="pending" class="btn btn-light ms-3" @click="retry" :disabled="saving">Retry save</button></div><div class="exam-layout"><section class="question-panel panel" v-if="item"><div class="section-row"><span class="eyebrow">QUESTION {{item.question.number}} · {{index+1}} OF {{attempt.palette.length}}</span><button @click="bookmark" class="btn btn-light btn-sm"><Bookmark :size="17" :fill="item.bookmarked?'currentColor':'none'"/>{{item.bookmarked?'Bookmarked':'Bookmark'}}</button></div><div class="question-content"><div class="question-meta"><span>{{item.question.kind.replace('_',' / ')}}</span><span>{{item.question.marks===null?'Marks not specified':'+'+item.question.marks+' marks'}}</span><span v-if="item.question.negative_marks">−{{item.question.negative_marks}} incorrect</span></div><QuestionContent :text="item.question.text" :images="item.question.images.filter(i=>!i.option_key)" class="question-stem"/>
<div v-if="['MCQ','MSQ','TRUE_FALSE'].includes(item.question.kind)" class="options"><button v-for="(o,oi) in item.question.options" class="option" :class="{chosen:Array.isArray(value)&&value.includes(o.key)}" :disabled="saving||!!pending" @click="option(o.key)"><span class="option-key">{{String.fromCharCode(65+oi)}}</span><div><QuestionContent :text="o.text" :images="item.question.images.filter(i=>i.option_key===o.key)"/></div><Check v-if="Array.isArray(value)&&value.includes(o.key)" :size="20" class="ms-auto"/></button><p v-if="item.question.kind==='MSQ'" class="muted small">Select every correct option. Exact-match scoring applies.</p></div><label v-else-if="item.question.kind==='NAT'">Your numerical answer (number or fraction)<input type="text" inputmode="decimal" class="form-control numeric-answer" :value="value" @input="editText($event.target.value)" @blur="flushText()" :disabled="navigating"></label><label v-else-if="item.question.kind==='SHORT_TEXT'">Your answer (follow the source format)<input class="form-control" type="text" :value="value" @input="editText($event.target.value)" @blur="flushText()" :disabled="navigating" maxlength="20000"></label><label v-else>Your answer<textarea class="form-control long-answer" :value="value" @input="editText($event.target.value)" @blur="flushText()" :disabled="navigating" maxlength="20000" rows="9"></textarea><small>Written and code responses remain ungraded. Code is not executed.</small></label>
<div v-if="feedback&&attempt.mode==='practice'" class="feedback"><span class="eyebrow">{{feedback.outcome}}</span><h3>Correct answer</h3><AnswerValue :question="item.question" :value="feedback.answers"/><MathText :text="feedback.explanation||'Solution explanation not available.'"/></div></div><div class="save-status" role="status"><Check v-if="!pending" :size="15"/><WifiOff v-else :size="15"/>{{saved}}</div><div class="question-actions"><button class="btn btn-review" :disabled="saving||!!pending||navigating" @click="markNext">Mark for review &amp; next</button><button class="btn btn-light" :disabled="saving||!!pending" @click="answer(null)">Clear response</button><button class="btn btn-review" :disabled="saving||!!pending" @click="persist({question_id:current.question_id,marked:!item.marked})"><Flag :size="16"/>{{item.marked?'Unmark review':'Mark for review'}}</button><div class="spacer"></div><button class="btn btn-light" @click="open(index-1)" :disabled="index===0||saving||!!pending"><ChevronLeft :size="17"/>Previous</button><button class="btn btn-primary" @click="open(index+1)" :disabled="index===attempt.palette.length-1||saving||!!pending">Save &amp; next<ChevronRight :size="17"/></button></div></section>
<aside class="palette-panel panel"><button class="palette-toggle text-btn" @click="showPalette=!showPalette">Question palette {{showPalette?'−':'+'}}</button><div :class="{'mobile-hidden':!showPalette}"><h2 class="palette-heading">Question palette</h2><p class="muted small">{{attempt.palette.filter(p=>p.state.startsWith('ANSWERED')).length}} / {{attempt.palette.length}} answered</p><div class="palette"><button v-for="(p,n) in attempt.palette" :class="[p.state,{current:n===index}]" :aria-label="'Question '+(p.number||n+1)+', '+paletteLabel(p.state)" :aria-current="n===index?'step':undefined" :disabled="saving||!!pending" @click="open(n)">{{p.number||n+1}}</button></div><div class="palette-legend"><div v-for="s in ['ANSWERED','NOT_ANSWERED','NOT_VISITED','MARKED_FOR_REVIEW','ANSWERED_AND_MARKED_FOR_REVIEW']"><i :class="s"></i>{{paletteLabel(s)}}</div><div><i class="current"></i>Current question</div></div></div><button class="btn btn-primary w-100 mt-3" @click="confirm=true" :disabled="saving||!!pending">Submit {{attempt.mode==='exam'?'exam':'practice'}}</button><p class="small muted mt-3 mb-0">← / → previous / next question. Responses are saved temporarily during this session. {{attempt.mode==='exam'?'The server enforces the deadline, including after refresh.':'Answers appear after you respond.'}}</p></aside></div>
<div v-if="switchDialog" class="modal-backdrop-custom"><section class="confirm-dialog panel" role="dialog" aria-modal="true" aria-labelledby="switch-title"><h2 id="switch-title">Switch to {{attempt.mode==='exam'?'practice':'exam'}}?</h2><p>Your selected answers, review marks and current question carry forward. No permanent attempt history is kept.</p><p v-if="attempt.mode==='exam'">The current timed result remains available temporarily; switching does not replace your latest paper score.</p><template v-else><p>The timed continuation is labelled assisted because practice may already have shown answers.</p><label>Timer (minutes)<input class="form-control" type="number" min="1" max="480" v-model="switchMinutes"></label></template><div class="d-flex gap-3 mt-3"><button class="btn btn-light" @click="switchDialog=false">Cancel</button><button class="btn btn-primary" @click="switchMode">Switch mode</button></div></section></div><div v-if="instructions" class="modal-backdrop-custom"><section class="confirm-dialog panel" role="dialog" aria-modal="true" aria-labelledby="instructions-title"><h2 id="instructions-title">Exam instructions</h2><ul><li>Use the question palette or ← / → keys to navigate. Arrow shortcuts are disabled while typing.</li><li>Responses save automatically. Use Clear response to remove your answer.</li><li>Green: answered. Orange: visited without an answer. Grey: not visited. Purple: marked for review. Purple with a tick: answered and marked.</li><li>Marked answers are included in scoring.</li><li>The server submits timed attempts when time expires. Practice is untimed.</li><li>Keys and explanations appear after submission in exam mode.</li></ul><button class="btn btn-primary" @click="instructions=false">Back to questions</button></section></div><div v-if="confirm" class="modal-backdrop-custom"><section class="confirm-dialog panel" role="dialog" aria-modal="true" aria-labelledby="submit-title"><h2 id="submit-title">Finish this attempt?</h2><p>You have answered {{attempt.palette.filter(p=>p.state.startsWith('ANSWERED')).length}} of {{attempt.palette.length}} questions. Marked answers are included in scoring.</p><div class="d-flex gap-3"><button class="btn btn-light" @click="confirm=false">Keep working</button><button class="btn btn-primary" @click="submit">Submit attempt</button></div></section></div></template><p v-else>Loading attempt…</p></template>
