<script setup>
import {ref,watch} from 'vue';import {api} from './api';import MathText from './MathText.vue';
const props=defineProps({paperId:[String,Number]});const emit=defineEmits(['saved']);
const text=ref(''),rows=ref([]),error=ref(''),notice=ref(''),busy=ref(false),validated=ref(''),replaceExisting=ref(false);
watch(()=>props.paperId,()=>{text.value='';rows.value=[];validated.value='';notice.value='';error.value=''});
watch(replaceExisting,()=>{rows.value=[];validated.value=''});
watch(text,()=>{rows.value=[];validated.value='';notice.value=''});
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
async function exportPaper(){await run(async()=>{const data=await api('/admin/ai-solutions/papers/'+props.paperId+'/export');download(data,'pyq-paper-'+props.paperId+'-for-solutions.json');notice.value='Paper exported. Share this JSON and the source PDF in chat; import the returned solution JSON here.'})}
async function readFile(e){await run(async()=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000)throw Error('Use a JSON file smaller than 2 MB.');text.value=await f.text()})}
async function preview(){await run(async()=>{const bundle=JSON.parse(text.value);const d=await api('/admin/ai-solutions/import',{method:'POST',body:{paper_id:Number(props.paperId),bundle,replace_existing:replaceExisting.value}});rows.value=d.items;validated.value=text.value})}
async function save(){await run(async()=>{if(validated.value!==text.value||!rows.value.length)throw Error('Preview the current solution JSON first.');const d=await api('/admin/ai-solutions/import',{method:'POST',body:{paper_id:Number(props.paperId),bundle:JSON.parse(text.value),save:true,replace_existing:replaceExisting.value}});notice.value=d.saved+' solutions saved. Review and publish from the question list.';validated.value='';rows.value=[];emit('saved')})}
</script>
<template><section class="panel mt-3"><h3>Paste / upload paper solutions</h3><p>Select a paper above. Export its question IDs and versions, share the JSON and source PDF in chat, then paste or upload the returned solution JSON. Preview maths before saving. Existing solutions are protected unless replacement is enabled. Replaced published solutions return to review before publishing again.</p><p v-if="error" class="alert alert-danger">{{error}}</p><p v-if="notice" class="alert alert-success">{{notice}}</p><button class="btn btn-light" :disabled="busy||!paperId" @click="exportPaper">Export paper for solutions</button><label class="d-block my-3">Upload solution JSON<input class="form-control" type="file" accept=".json,application/json" :disabled="busy||!paperId" @change="readFile"></label><textarea aria-label="Paper solution JSON" class="form-control" rows="8" v-model="text" :disabled="busy||!paperId" placeholder="Paste the complete solution JSON here"></textarea><label class="d-block mt-3"><input type="checkbox" v-model="replaceExisting" :disabled="busy"> Replace existing solutions for questions included in this JSON</label><div class="d-flex flex-wrap gap-2 my-3"><button class="btn btn-light" :disabled="busy||!paperId||!text" @click="preview">Preview solutions</button><button class="btn btn-primary" :disabled="busy||!rows.length||validated!==text" @click="save">Save imported drafts</button><span v-if="busy" role="status">Processing…</span></div><article v-for="r in rows" :key="r.question_id" class="panel mt-3"><strong>Question {{r.number}} · {{r.status}} {{r.replacing?'· replaces existing solution':''}}</strong><p>Final answer: {{r.final_answer}}</p><p v-for="c in r.checks" class="alert alert-warning">{{c}}</p><MathText :text="r.text" inline-dollar/></article></section></template>
