<script setup>
import {ref} from 'vue';import {api} from './api';
const props=defineProps({paperId:Number,paperName:String});const emit=defineEmits(['close','updated']);const file=ref(null),job=ref(null),busy=ref(false),error=ref('');
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=e.message}finally{busy.value=false}}
async function upload(){await run(async()=>{if(!file.value)throw Error('Choose a PDF.');const data=new FormData();data.append('file',file.value);const d=await api('/admin/papers/'+props.paperId+'/replacement',{method:'POST',form:data});job.value=d.file;emit('updated')})}
async function refresh(){await run(async()=>{job.value=(await api('/admin/ingestion/'+job.value.id)).file;emit('updated')})}
async function process(){await run(async()=>{job.value=(await api('/admin/ingestion/'+job.value.id+'/process-now',{method:'POST',body:{}})).file;emit('updated')})}
</script>
<template><div class="modal-backdrop-custom"><section class="confirm-dialog panel replacement-dialog" role="dialog" aria-modal="true" aria-labelledby="replacement-title"><h2 id="replacement-title">Upload replacement PDF</h2><p>{{paperName||'Paper #'+paperId}}</p><p class="muted small">Updates this existing paper. Existing valid questions stay safe if extraction fails. Admin corrections and hidden questions are preserved.</p><p v-if="error" class="alert alert-danger" role="alert">{{error}}</p><form @submit.prevent="upload"><label>Corrected PDF<input class="form-control" type="file" accept="application/pdf" @change="file=$event.target.files[0]" required></label><button class="btn btn-primary mt-3" :disabled="busy||!file">{{busy?'Working…':'Upload PDF'}}</button></form><section v-if="job" class="mt-3"><strong>{{job.effective_status||job.status}}</strong><p v-if="job.error" class="alert alert-danger mt-2">{{job.error}}</p><div class="d-flex gap-2 flex-wrap"><button v-if="job.status==='QUEUED'" class="btn btn-primary" :disabled="busy" @click="process">Process now</button><button class="btn btn-light" :disabled="busy" @click="refresh">Refresh status</button></div><p v-if="busy" role="status" class="mt-3">Processing can take a little time. Please keep this window open.</p><details><summary>Processing details</summary><pre>{{JSON.stringify({warnings:job.warnings,events:job.events},null,2)}}</pre></details></section><button class="btn btn-light mt-3" :disabled="busy" @click="emit('close')">Close</button></section></div></template>
