<script setup>
import {ref,onMounted,onUnmounted,computed} from 'vue';import {api,loadCatalog} from './api';
const courses=ref([]),meta=ref({exams:[],terms:[]}),form=ref({course_id:'',exam_type_id:'',term_id:'',name:''}),file=ref(null),job=ref(null),paper=ref(null),busy=ref(false),error=ref('');let poll;
const status=computed(()=>job.value?.effective_status||job.value?.status||'');
const failed=computed(()=>['EXTRACTION_FAILED','PROCESSING_FAILED'].includes(status.value));
const done=computed(()=>['AVAILABLE','PARTIAL'].includes(status.value));
const stage=computed(()=>busy.value?'Uploading…':failed.value?'Extraction Failed ✗':done.value?'Completed ✓':status.value==='QUEUED'?'Waiting for processing worker…':job.value?.events?.at(-1)?.stage==='VALIDATING'?'Validating…':job.value?.events?.at(-1)?.stage==='DETECTING_ANSWERS'?'Detecting answers…':status.value==='PROCESSING'?'Processing PDF / extracting questions…':'');
onMounted(async()=>{try{const catalog=await loadCatalog();courses.value=catalog.courses;meta.value=catalog.meta}catch(e){error.value=e.message}});
onUnmounted(()=>clearInterval(poll));
async function refresh(){try{const d=await api('/admin/ingestion/'+job.value.id);job.value=d.file;paper.value=d.paper;if(done.value||failed.value)clearInterval(poll)}catch(e){error.value=e.message}}
function watchJob(){clearInterval(poll);poll=setInterval(refresh,1500);refresh()}
async function upload(){busy.value=true;error.value='';try{if(!file.value)throw Error('Select a PDF.');const data=new FormData();Object.entries(form.value).forEach(([k,v])=>data.append(k,v));data.append('file',file.value);const d=await api('/admin/upload-pyq',{method:'POST',form:data});job.value=d.file;paper.value=d.paper;watchJob()}catch(e){error.value=e.message}finally{busy.value=false}}
async function retry(){try{await api('/admin/ingestion/'+job.value.id+'/retry',{method:'POST'});watchJob()}catch(e){error.value=e.message}}
</script>
<template><section class="panel"><h2>Upload PYQ PDF</h2><p class="muted">Choose the paper metadata and upload. Processing and student availability are automatic.</p><p v-if="error" class="alert alert-danger" role="alert">{{error}}</p><form @submit.prevent="upload"><div class="form-grid"><label>Course<select class="form-select" v-model="form.course_id" required aria-label="Upload course"><option value="">Select Course</option><option v-for="c in courses" :value="c.id">{{c.name}}</option></select></label><label>Exam type<select class="form-select" v-model="form.exam_type_id" required aria-label="Upload exam type"><option value="">Select Exam Type</option><option v-for="e in meta.exams" :value="e.id">{{e.name}}</option></select></label><label>Term / Year<select class="form-select" v-model="form.term_id" required aria-label="Upload term"><option value="">Select Term</option><option v-for="t in meta.terms" :value="t.id">{{t.name}}</option></select></label><label>Paper title (optional)<input class="form-control" v-model="form.name" placeholder="Uses the PDF filename when blank"></label></div><label class="d-block my-3">PDF file<input class="form-control" type="file" accept="application/pdf" required @change="file=$event.target.files[0]" aria-label="Upload PDF file"></label><button class="btn btn-primary" :disabled="busy||job&&!done&&!failed">{{busy?'Uploading…':'Upload PDF'}}</button></form><section v-if="job" class="mt-4" aria-live="polite"><h3>{{stage}}</h3><p v-if="status==='QUEUED'" class="muted">The local launcher starts the processing worker automatically.</p><p v-if="done">{{paper?.question_count}} questions are ready. {{status==='PARTIAL'?'Some records were incomplete; reliable questions are available.':''}}</p><p v-if="job.error" class="alert alert-danger">{{job.error}}</p><a v-if="done" :href="'#/paper/'+paper.id" class="btn btn-primary">Open paper →</a><button v-if="failed" @click="retry" class="btn btn-outline-primary">Retry</button><details class="mt-3"><summary>Processing log</summary><ol><li v-for="e in job.events">{{e.stage}} — {{e.message}}</li></ol></details></section></section></template>
